### ISSUE TITLE
sql to determine version number is not deterministic

### ISSUE THREAD

**Issue by robacarp** [vladfaust/migrate.cr#12]
My experience with postgres shows that a `SELECT` statement cannot be trusted to order the data in a consistent way, especially with older tables. While porting some unrelated migration history over to migrate.cr, I found that I needed to change the current_version sql slightly:

```diff
    def current_version
-      query = "SELECT %{column} FROM %{table}" % {
+      query = "SELECT %{column} FROM %{table} ORDER BY %{column} DESC" % {
        column: @column,
        table:  @table,
      }

      @db.scalar(query).as(Int32 | Int64)
    end
```

It's possible I'm misunderstanding the point of what that method does, but this tweak got it working for me.

**Comment by vladfaust** [comment]
@robacarp there is a *single* version value in migrate.cr's table, no need for ordering then. You may be confused with micrate's tons of rows 😊

**Comment by robacarp** [comment]
Great context, thanks.
