### ISSUE TITLE
Version numbers do not match

### ISSUE THREAD

**Issue by t-richards** [vladfaust/migrate.cr#15]
## Version information

- Crystal: `0.25.0`
- migrate.cr: `0.2.2`

## Problem summary

The version numbers contained within code/metadata do not match the git tag. This causes funny behavior in `shards`, For example, running `$ shards check` in a project which depends on migrate.cr will always show that the dependencies are not satisfied, which will cause it to re-fetch all dependencies (this is slow and annoying, especially with lots of deps)

## Mismatched version locations

 - https://github.com/vladfaust/migrate.cr/blob/v0.2.2/shard.yml#L2
 - https://github.com/vladfaust/migrate.cr/blob/v0.2.2/src/migrate/version.cr#L2

**Comment by vladfaust** [comment]
Wow, never thought of that. So, each small commit would require to bump versions in those two files? That's mess.

**Comment by t-richards** [comment]
>each small commit would require to bump versions in those two files? 

Not necessarily each commit. But each tagged release, yes.

**Comment by vladfaust** [comment]
There is no need in duplication of a tag within the code itself. It's just a waste of time (waste bigger than re-fetching). Version locking works perfectly with tags-only approach - shards installed and udpated correctly and the repository isn't bloated with useless bumps.

Your issue looks more like `shards` issue itself. I encourage you to create an issue there to discuss this.

Or you can try to convince me more 😃

**Comment by t-richards** [comment]
You're right, updating `Migrate::VERSION` in the code isn't strictly necessary, but nice to have. I don't have a good argument for why shards needs the version in `shards.yml`, since it fetches version information from the tags anyway, but this seems to be how it works today.
